### ISSUE TITLE
More datail- running the script

### ISSUE THREAD

**Issue by susuhahnml** [kstrauch94/benchmark-tool-guide#1]
After working with the benchmark-tool I feel that one missing thing is in the section of running the script. I would add there a bit more explanation on how in the case of an .sh file being created, then in such file a call to sbatch will be made.

**Comment by kstrauch94** [comment]
Hi Susana, I have written a couple of lines that address this shortly. Can you see them and check that they will avoid your issue for future users? This is the link to the [commit](https://github.com/kstrauch94/benchmark-tool-guide/commit/cb30acb3664c9a8379e7d4a84afa3d74582f78a5)

Thank you

**Comment by susuhahnml** [comment]
Seams perfect. :) We were also discussing adding a link to scrips like the one from javier that might help give an idea on how to integrate it. But i am not sure where would be the best part to add this.

**Comment by kstrauch94** [comment]
Thanks. I will merge it to master now. I would have to add that somewhere at the end of the guide or in a separate section altogether.

I'm closing the issue.
